version: "3"

services:
  stationeers:
    image: ghcr.io/ralyon76/stationeers-server:main
    container_name: stationeers
    volumes:
      - ./stationeers/data:/home/steam/stationeers
    ports:
      - 27016:27016/udp
    environment:
      SERVER_NAME: A Docker Server
      WORLD_TYPE: mars
      SERVER_PASSWORD: yourpass
      SERVER_PUBLIC: "false"
